[project]
name = "book-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.6.7",
    "openai>=1.106.1",
    "python-dotenv>=1.1.1",
    "xhtml2pdf>=0.2.17",
]
